// <auto-generated />
using BussesRouteMiniProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BussesRouteMiniProject.Migrations
{
    [DbContext(typeof(BussesRouteDbContext))]
    partial class BussesRouteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BussesRouteMiniProject.Data.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Busses");
                });

            modelBuilder.Entity("BussesRouteMiniProject.Data.Models.BussesStops", b =>
                {
                    b.Property<int>("StopId")
                        .HasColumnType("int");

                    b.Property<int>("BussId")
                        .HasColumnType("int");

                    b.HasKey("StopId", "BussId");

                    b.HasIndex("BussId");

                    b.ToTable("BussesStops");
                });

            modelBuilder.Entity("BussesRouteMiniProject.Data.Models.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("BussesRouteMiniProject.Data.Models.BussesStops", b =>
                {
                    b.HasOne("BussesRouteMiniProject.Data.Models.Bus", "Bus")
                        .WithMany("Stops")
                        .HasForeignKey("BussId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BussesRouteMiniProject.Data.Models.Stop", "Stop")
                        .WithMany("Busses")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("BussesRouteMiniProject.Data.Models.Bus", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("BussesRouteMiniProject.Data.Models.Stop", b =>
                {
                    b.Navigation("Busses");
                });
#pragma warning restore 612, 618
        }
    }
}
